### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by simplew2011** [MarkHershey/arxiv-dl#5]
```paper 2105.06070v1 1804.04829v2 2201.07422v1```
```
Traceback (most recent call last):
  File "/home/wzp/anaconda3/envs/python3.8/bin/paper", line 45, in <module>
    check_update()
  File "/home/wzp/anaconda3/envs/python3.8/lib/python3.8/site-packages/arxiv_dl/updater.py", line 28, in check_update
    latest_version = check_latest_version()
  File "/home/wzp/anaconda3/envs/python3.8/lib/python3.8/site-packages/arxiv_dl/updater.py", line 10, in check_latest_version
    response = requests.get(pypi_url)
  File "/home/wzp/anaconda3/envs/python3.8/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/wzp/anaconda3/envs/python3.8/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wzp/anaconda3/envs/python3.8/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wzp/anaconda3/envs/python3.8/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/wzp/anaconda3/envs/python3.8/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/arxiv-dl/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7f54990640>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Comment by MarkHershey** [comment]
Hi @simplew2011 , I am unable to replicate this error. Based on the error msg provided, it is likely due to the `pypi.org` being unavailable. It might be a temporary thing, or something wrong with your network condition. Please try connecting to another network and try using the command again.

**Comment by simplew2011** [comment]
Do you consider adding IP proxy functionality or interfaces？

**Comment by MarkHershey** [comment]
> Do you consider adding IP proxy functionality or interfaces？

Everyone's network condition can be quite different, proxy should not be done at this application level I believe.

**Comment by MarkHershey** [comment]
I just pushed a minor version (30be9a44bb74c039bfea04e7d796485efe275a2f) to handle this error further in case `pypi.org` is not available during the function call `check_update()`. If your network has an issue with `pypi.org` only, the new version should not throw an error anymore.
